### ISSUE TITLE
Entry component styling

### ISSUE THREAD

**Issue by pixx3l** [megdadkins7/budget#7]
### Requirements

* [x] Amount is bold (explanation on google font weights [here](https://stackoverflow.com/questions/7256065/specifying-style-and-weight-for-google-fonts)
* [x] Amount and title should have 15px spacing between them. The title is flexible (as is the amount) so you'll probably need to use flex, and a `margin-left` on the amount so regardless of the width of the two, theres alway 15px to the left of amount
* [x] Entry div should 'seran-wrap' its contents. This means that its' only as wide as its' text children, and if one grows (titles have diff widths) the Entry div grows with it. `display: flex` will help with this.

**Comment by pixx3l** [comment]
<img width="166" alt="entry" src="https://user-images.githubusercontent.com/34278658/60348680-12b88880-998e-11e9-9af6-3f454bdc903e.png">

**Comment by megdadkins7** [comment]
addressed in #8
