### ISSUE TITLE
Include Google font weights inside global import

### ISSUE THREAD

**Issue by pixx3l** [megdadkins7/budget#9]
Fonts (in general) are designed as a unique set of characters based on a weight/style (bold/italic). This means that something like `Roboto Regular` is a different glyph set from `Roboto Bold`. When we import a font, we want to include all of the desired weights (e.g. medium, bold, bold-italic) that we need. In our case, I think we use regular and medium, which means `400, 500`. If you're wondering why `font-weight` has been working, the browser will attempt to apply a style value even if it doesn't exist, so sometimes it can 'create' the illusion of bold text, but it's better to be sure that the weight you're applying is there. 

As for adding the weights, I attached two screenshots from Google Fonts that show how to select the desired font weights (in their UI), and what the import statement ends up looking like when you include more than one weight or style. If you know the weight number, you can just add it to the import statement in your code yourself, otherwise you can select it in google and it'll create the import string for you. 

Steps to add font weights:

1. Go to google fonts .com
2. Find the font you want (e.g. Roboto) and click the `+` button to get the bottom left panel to show up
3. Expand the font panel by clicking on it
4. Go to the 'Customize', and make sure the weights and styles you want are selected
5. Go to the 'Embed' tab, and click on `@import`. You'll get the css import rule to use in your code

**Comment by pixx3l** [comment]
<img width="601" alt="Screen Shot 2019-07-02 at 3 28 22 PM" src="https://user-images.githubusercontent.com/34278658/60541157-f2b2fd00-9cde-11e9-930f-a956eaf532e7.png">
<img width="602" alt="Screen Shot 2019-07-02 at 3 28 30 PM" src="https://user-images.githubusercontent.com/34278658/60541159-f3e42a00-9cde-11e9-913f-6218fd1f2c9f.png">

**Comment by megdadkins7** [comment]
addressed in #8
